INSERT INTO TB_AUTHOR(ID, NAME, AGE) VALUES(1, 'JANETE SIQUEIRA', 35);
INSERT INTO TB_AUTHOR(ID, NAME, AGE) VALUES(2, 'MARTIN FOWLER', 47);

INSERT INTO TB_BOOK(ID, NAME, CHAPTERS, PAGES, ISBN, PUBLISH_NAME, AUTHOR_ID) VALUES(1, 'VOLTA AO MUNDO EM UM DIA', 20, 300, '22222222', 'FICÇÃO CIENTIFICA', 1);
INSERT INTO TB_BOOK(ID, NAME, CHAPTERS, PAGES, ISBN, PUBLISH_NAME, AUTHOR_ID) VALUES(2, 'ARQUITETURA LIMPA', 20, 300, '111111111', 'LIVRO DE TI', 2);
INSERT INTO TB_BOOK(ID, NAME, CHAPTERS, PAGES, ISBN, PUBLISH_NAME, AUTHOR_ID) VALUES(3, 'EXPLORAÇÃO ESPACIAL', 20, 300, '33333333', 'FICÇÃO', 1);